### PR TITLE
0.8.0 rc2

### PR DESCRIPTION
**Pull request by vaphes**
Update to new 0.8.0 version. Thanks in advance for @perfalle and @m29h for the contributions.

### CODE REVIEW

**Comment by m29h** [comment]
I just noticed that the example in `Readme.md` is not compatible with the v0.8.0 API at all any more due to breaking changes. I recommend merging pull request #9 before releasing the branch.

**Comment by paulocoutinhox** [comment]
Can you merge this?

**Comment by paulocoutinhox** [comment]
Hi @vaphes. Do you go modify it? Or need help to fix the conflicts?

**Comment by vaphes** [comment]
> Hi @vaphes. Do you go modify it? Or need help to fix the conflicts?

I´d really appreciate if you could help me out on this one!
Already added you as a collaborator.

Thanks in advance!

**Pull request merged**
