### PR TITLE
adding dataclass to record model

### LINKED ISSUE #27: add json serialization support for various types
Great work on this SDK.

This is a request for an enhancement to support JSON serialization for the different types supported

Eg:

```python
import json
from pocketbase import PocketBase 

client = PocketBase('http://127.0.0.1:8090')

# authenticate as regular user
user_data = client.collection("users").auth_with_password("foo@bar.com", "thisIsAFaksePassword123")

# get a compliance report
report = client.collection("compliance").get_list()

print(json.dumps(report, indent=4))
```

This currently results in:

```
Traceback (most recent call last):
  File "/Users/dansikes/go/src/github.com/dsikes/equip/scripts/test.py", line 12, in <module>
    print(json.dumps(report, indent=4))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListResult is not JSON serializable
```

Happy to work on a PR, but wanted to see if this was something you'd consider before doing so.

Thanks!

### PR DESCRIPTION
**Pull request by dsikes**
By adding data class support to the record model, you can simply use data class.asdict to have a JSON serializable object.
Here is a simple example:

```python
import json
import dataclasses
from pocketbase import PocketBase 

client = PocketBase('http://127.0.0.1:8090')

client.admins.auth_with_password('foo@bar.com', 'fakepassword123')

# get a list of things from a collection
report = client.collection("users").get_list()

j = dataclasses.asdict(report)

print(json.dumps(j, indent=4))
```

Which gives 

```json
{
    "page": 1,
    "per_page": 30,
    "total_items": 2,
    "total_pages": 1,
    "items": [
        {
            "collection_id": {
                "avatar": "",
                "collectionId": "_pb_users_auth_",
                "collectionName": "users",
                "created": "2023-02-27 05:42:17.112Z",
                "email": "foobar@gmail.com",
                "emailVisibility": false,
                "id": "49lzk2x2ta1v60h",
                "name": "Dan Sikes",
                "phone": 9194023592,
                "reports_to": "sr8397188ya59y9",
                "role": "Crew Leader",
                "updated": "2023-03-01 21:28:05.160Z",
                "username": "dsikes",
                "verified": true
            },
            "collection_name": "",
            "expand": {}
        },
        {
            "collection_id": {
                "avatar": "",
                "collectionId": "_pb_users_auth_",
                "collectionName": "users",
                "created": "2023-02-27 07:02:45.896Z",
                "email": "foobar7@gmail.com",
                "emailVisibility": false,
                "id": "sr8397188ya59y9",
                "name": "Blueberry",
                "phone": 4785758205,
                "reports_to": "",
                "role": "CEO",
                "updated": "2023-02-27 16:47:27.613Z",
                "username": "blueberry",
                "verified": true
            },
            "collection_name": "",
            "expand": {}
        }
    ]
}
```

This would close #27

### CODE REVIEW

**Comment by dsikes** [comment]
@vaphes any thoughts on the proposed changes?

**Comment by ronnyandre** [comment]
This code doesn't work with custom collections. I get the following error:

    TypeError: Object of type Record is not JSON serializable

**Comment by ronnyandre** [comment]
This is a great addition to Pocketbase!

**Review by vaphes — COMMENTED** [review]
Looks good, I think it would improve a lot the usability of the lib.
Aproved

**Review by vaphes — APPROVED** [review]

**Pull request merged**
